text = input("Enter a string: ")

print("\nOriginal String :", text)
print("Upper           :", text.upper())
print("Lower           :", text.lower())
print("Title           :", text.title())
print("Capitalize      :", text.capitalize())
print("Swapcase        :", text.swapcase())
print("Length          :", len(text))
print("Count of 'a'    :", text.count('a'))
print("Find 'a'        :", text.find('a'))
print("Replace 'a'->'@':", text.replace('a', '@'))
print("Starts with 'H' :", text.startswith('H'))
print("Ends with '!'   :", text.endswith('!'))
print("Is Alphabet     :", text.isalpha())
print("Is Digit        :", text.isdigit())
print("Is Alphanumeric :", text.isalnum())
print("Is Lower        :", text.islower())
print("Is Upper        :", text.isupper())
print("Is Title        :", text.istitle())
print("Remove Spaces   :", text.strip())
print("Left Strip      :", text.lstrip())
print("Right Strip     :", text.rstrip())
print("Split           :", text.split())
print("Join with '-'   :", "-".join(text))
print("Reverse         :", text[::-1])
